---

language: python
python:
  - '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_ed371e731034_key -iv $encrypted_ed371e731034_iv -in gce.tar.enc -out gce.tar -d
  - tar -xvf gce.tar && rm -f gce.tar
  - mkdir -p ~/.gcp && mv -f ${GCE_SA_FILE} ~/.gcp && chmod 0600 ~/.gcp/${GCE_SA_FILE}
  - mv -f ${GCE_SSH_FILE}* ~/.ssh && chmod 0600 ~/.ssh/${GCE_SSH_FILE}*
  - pwd && ls -a

install:
  - pip install -r requirements.txt

before_script:
  - ansible --version && molecule --version

script:
#  - molecule --debug test --destroy never
  - molecule test --destroy never

after_script:
#  - molecule --debug destroy 4
  - molecule destroy
  - rm -rf ~/.gcp && rm -f ~/.ssh/${GCE_SSH_FILE}*
