language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_dbee582e6dc3_key -iv $encrypted_dbee582e6dc3_iv
  -in gce.tar.enc -out gce.tar -d
- tar -xvf gce.tar && rm -f gce.tar
- ls -la
- chmod 0600 infra-265717-a32f80d8cfce.json
- mv -f google_compute_engine* ~/.ssh && chmod 0600 ~/.ssh/google_compute_engine*
- pwd && ls -a
install:
- pip install -r requirements.txt
before_script:
#- ansible --version && molecule --version
script:
- molecule --debug test --destroy never
after_script:
- molecule --debug destroy
notifications:
  slack:
    rooms:
      secure: K3FE2iLb/uU0Qqf8DXrGezhzYL1TsDVBvHwCRHap6WSSfGPxbaHGoL3dm755Do7NYp+ytFcFiveb+094tDRr31p4wQjpSgrbbpLEeYEOqm9hCzA5Cvv+CBbea0uv1jGpgIFnHQx1e+o+q9RL3jIfSdyhvJxG7H5CXSLR+mqMZPFoAGDAwA6KpuiabwQP0oJYauiarInjw4TWFomABlLRUhoj9sa4NJ5Pz/94sd3RPBDwdnJ9TpMVyDBhS2xqOFQgg1VSvv3N5U5Y8i+4UohLGOUgpvQJo1bWln/8luKemCVyACn2xLlZOUp/+tHuPFUy8cJFPKjf4ftMb7mw3RG6Ny6ZigVreJ0SFXaCwB6CEPjjtCjr3nx9zBjOV7Bxxou4GoMGkzbIq0peKbQYpcq2klc0nmYkM/upHGZW5dmTu4zPjYl+NGdX7IuIM33vIhObBqOVao/2D0Im2IFhFGHHEu1aHC7zw/4yp4Qrq0jRQTuISCokRmZ4PnGQeYVpuNEZ/s/726z2bu0OmgwuwzzsEf6zXTeSiZ0AflqeozfCpJ8Zh8fPcIUpi7oBN0dsafuLNQ1S9qf2dVQPBpFTIZgSL7hrSONmR3nsyNTCVwzR1Bkvs3k1+YyQobZZFf8xfU3KbgHbMn06X/f2dnqji7gx7yLODo/O3jTQY3y//907OqU=
env:
  global:
  - MOLECULE_NO_LOG=0
  - GCE_CREDENTIALS_FILE=/home/travis/build/lebedevdg/ansible_role_db/infra-265717-a32f80d8cfce.json
  - secure: b39X793W3ErZQHqyJVhQ7kEdG4PnaTNJ9kJASPmVunjfdDevYbXWO+n98p9yxnlhqV7fVLL6OHXGLE19EwmPakGL5BJry4ggHabSyCQB4XpIPyuhEEeJ7YIDqagG3GTC4JrX0xnoMm9HeR6WJNFeKYa+laVC7BES/X0oLnUrpmr287zrmHxzzqkMMe7oQXleQonRP7Or3mSLHa8ru4Rrs7fgVBsyEOtDkq3dNiEODEa8vtosEwYrQ2waRfBWJdXWyj6+0qbxs23qiIDUrgHb03B4Jda1H3HME+tbF2xUHeMLIHOFm+c4fZd6f6hpLS8sqKSyc8PZur4c//7FC1TsrafkX+409tEFW5u1JZgv960eZ0z5ngszpcDFAMfoxI7WgRtBV4CRLqUjEg1Watt53/PxpcOG3iddCtcS3padHf4CUSMOfd5P1nCnXt2Ixbn4SMpThaYeYs7YP3b08sxUII1yF/V4ICVfel9tn+r4hAg9kYbOpQ0ocjoD1LX2pNKiJbNuPe+towU/EfzYEK/wmeX+X8Cc5C6Yvy0ieY13K+xbjnsUZNqTb53YG0/5lfdqVJs6tcywGB3NZqegxfvAoyXJhYbm+MTjDAideG1fPwm0DFnvv91nrDwm9i5uu7qiuzT0evhugIm2EGLwCPH/m/kdcMZa9lArk+20wD9NzYI=
  - secure: IXKdtqSl14wjEcpQsWuDjln2awOqHWC7KOyzhWbCuodKz0OYU2laSw84zDTizNqIN+Wgai4Z4DCvwYKTGC0TTikACSWC3HfMDk60P7qI4lbZMOX6ia6LDwUqD4DtIYY4qtf6hF/gRNu3cSBkig7Nq7x93Z/Uqc6zXLM0LRAyc3JYWRtbCTQ+2g/YxON5vOxc2sVRvjTcyC0FRNrTkPaACqJNMd42endDT+yLbPgua8sEJHc1lqVBoMAi7iuVR+ztS1jDL6UwMO9+SrXnKhCiGF4XjtwAzeHDmfW0QfvFw9VvlRx9BZJZCnAoihaNWjhl1FMQthIS6onqmqbAbSIQHW/qE/yJdAQ6dK0iD0H+rD5M2T8WvIDnNsix9IWw6IwqS4zXfd1Wj8wgGT+uBu/iRSL4Zr7wv2S3Fru0Mnqez8RcSMz0Dm8XmZdMMKytckge5Z6GgrXOIurfG4CZq9qvf9BsAneWlanWjBu3YVTESWS1+zTh/OWo+P+gaKFVJXKb7tPgxw4k8qW40+y1bwHpZPWukdEQbbHYy51n9iu7nMnK+lwci20wFsVzwgVejp5Dn+9lRFa4Pcb45Sl2GjcgK2y161gwEO4tNTf1Z3TEFZz23bL5JX1qCkM2FeBk1MNcFrKuRSmW6AcW0xV9xSdBbEi4M6JkHm509PSr0LuY5m0=
  - GCE_SSH_FILE=google_compute_engine
